apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: flink-task-manager-hpa
spec:
  maxReplicas: 4 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flink-taskmanager
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
        # We could use average value instead of target utilization. https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
        # type: AverageValue
        # averageValue: XXX 
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
  