# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: azure-managed-disk1
# spec:
#   accessModes:
#   - ReadWriteOnce
#   storageClassName: managed-premium
#   resources:
#     requests:
#       storage: 5Gi
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file1
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file2
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi