apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-test-job-jobmanager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-test-job
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink-test-job
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: xiefan46/flink-auto-scaling-prototype-image:latest
        imagePullPolicy: Always
        command: ["jobmanager.sh"]
        args: ["start-foreground"]
        resources:
          limits:
            cpu: 1
            memory: "3072Mi"
          requests:
            cpu: 0.5
            memory: "2048Mi"
        env:
          - name: JOB_MANAGER_RPC_ADDRESS
            value: flink-test-job-jobmanager-service
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob-server
        - containerPort: 8081
          name: webui
        livenessProbe:
          tcpSocket:
            port: 6123
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        securityContext:
          runAsUser: 9999  # refers to user _flink_ from official flink image, change if necessary
      volumes:
      - name: flink-config-volume
        configMap:
          name: test-job-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j-console.properties
            path: log4j-console.properties
          - key: log4j-cli.properties
            path: log4j-cli.properties

---

apiVersion: v1
kind: Service
metadata:
  name: flink-test-job-jobmanager-service
spec:
  type: LoadBalancer
  ports:
    - name: rpc
      port: 6123
    - name: blob-server
      port: 6124
    - name: webui
      port: 8081
  selector:
    app: flink-test-job
    component: jobmanager